import fs from "fs";
import path from "path";
import JSZip from "jszip";
import type { ProductSiteConfig } from "./types";

function escapeJson(str: string): string {
  return JSON.stringify(str);
}

export function buildSiteConfigFile(config: ProductSiteConfig): string {
  const siteConfig = {
    brandName: config.brandName,
    productName: config.productName,
    tagline: config.tagline,
    heroHeadline: config.heroHeadline,
    heroSubtext: config.heroSubtext,
    ctaText: config.ctaText,
    price: config.price,
    shippingMessage: config.shippingMessage,
    rating: config.rating,
    reviewCount: config.reviewCount,
    productDescription: config.productDescription,
    statsTitle: config.statsTitle,
    statsSubtitle: config.statsSubtitle,
    stats: config.stats,
    contactEmail: config.contactEmail,
    footerCopyright: config.footerCopyright,
    themeId: config.themeId || "classic",
    fontPairId: config.fontPairId || "inter",
    customAccentColor: config.customAccentColor || "",
    customButtonColor: config.customButtonColor || "",
    customBackgroundColor: config.customBackgroundColor || "",
    customTextColor: config.customTextColor || "",
    layoutId: config.layoutId || "classic",
  };

  return `export const siteConfig = ${JSON.stringify(siteConfig, null, 2)} as const;

export type SiteConfig = typeof siteConfig;
`;
}

export function buildReadme(config: ProductSiteConfig): string {
  const slug = config.brandName.toLowerCase().replace(/\s+/g, "-");
  return `# ${config.brandName} — Full-Stack Product Website

A **full-stack Next.js** product store generated by **Website Maker**.

## Stack

- **Next.js 16** App Router (frontend + API routes)
- **SQLite** database (\`data/store.db\`) — users, cart, orders, contact messages
- **bcrypt** password hashing + **httpOnly session cookies**

## Prerequisites

- Node.js 18.17+
- npm

## Quick Start

1. Extract this folder.

2. Install dependencies:

\`\`\`bash
npm install
\`\`\`

3. Copy environment file (optional for production):

\`\`\`bash
cp .env.example .env.local
\`\`\`

4. Start the dev server:

\`\`\`bash
npm run dev
\`\`\`

5. Open [http://localhost:3000](http://localhost:3000).

## API Endpoints

| Route | Method | Description |
|-------|--------|-------------|
| \`/api/auth/register\` | POST | Create account |
| \`/api/auth/login\` | POST | Sign in |
| \`/api/auth/logout\` | POST | Sign out |
| \`/api/auth/session\` | GET | Current user |
| \`/api/cart\` | GET/POST/PATCH/DELETE | Shopping cart |
| \`/api/orders\` | POST | Place order |
| \`/api/orders/track\` | POST | Track order by ID + email |
| \`/api/contact\` | POST | Contact form |
| \`/api/newsletter\` | POST | Email signup |
| \`/api/admin/dashboard\` | GET/POST/DELETE | Payment dashboard (store owner) |
| \`/api/admin/orders/[orderId]\` | PATCH | Update payment/shipping status |

## Payment dashboard

Visit [\`/dashboard\`](http://localhost:3000/dashboard) to manage orders and payments.

Default admin password: \`store-admin\` — set \`STORE_ADMIN_PASSWORD\` in \`.env.local\` for production.

## Customize Content

Edit \`lib/site-config.ts\` for product copy, pricing, and theme.

Replace \`public/product.jpg\` with your product image.

## Production

\`\`\`bash
npm run build
npm start
\`\`\`

Set \`SESSION_SECRET\` in \`.env.local\` for production deployments.

The SQLite database is created automatically in \`data/store.db\`.

---

Generated for **${config.productName}** · ${config.brandName}
`;
}

function buildPackageJson(config: ProductSiteConfig): string {
  const name = config.brandName.toLowerCase().replace(/\s+/g, "-") + "-site";
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint",
      },
      dependencies: {
        next: "16.2.9",
        react: "19.2.4",
        "react-dom": "19.2.4",
        "better-sqlite3": "^11.10.0",
        bcryptjs: "^3.0.2",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4",
        "@types/bcryptjs": "^2.4.6",
        "@types/better-sqlite3": "^7.6.13",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        eslint: "^9",
        "eslint-config-next": "16.2.9",
        tailwindcss: "^4",
        typescript: "^5",
      },
    },
    null,
    2,
  );
}

const STATIC_FILES: Record<string, string> = {
  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ["better-sqlite3"],
};

export default nextConfig;
`,
  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ),
  "postcss.config.mjs": `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`,
  "eslint.config.mjs": `import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts"]),
]);

export default eslintConfig;
`,
  "next-env.d.ts": `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
  ".gitignore": `# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files
.env*

# sqlite data
/data/

# typescript
*.tsbuildinfo
next-env.d.ts
`,
  "app/globals.css": `@import "tailwindcss";

:root {
  --background: #faf8f5;
  --foreground: #1a1a1a;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

body {
  background: var(--background);
  color: var(--foreground);
}
`,
  "app/page.tsx": `import { ProductSite } from "@/components/ProductSite";

export default function Home() {
  return <ProductSite />;
}
`,
};

const PRODUCT_COMPONENT_FILES = [
  "ProductSiteContext.tsx",
  "ProductFontLoader.tsx",
  "ProductReveal.tsx",
  "StatCounter.tsx",
  "Modal.tsx",
  "SiteModals.tsx",
  "ProductHeader.tsx",
  "ProductHero.tsx",
  "StatsSection.tsx",
  "ContactForm.tsx",
  "ProductFooter.tsx",
  "ProductSiteShell.tsx",
  "ProductHome.tsx",
  "ProductDetailsPage.tsx",
  "OrderDetailsPage.tsx",
  "LegalPageView.tsx",
  "PaymentDashboardPage.tsx",
  "ProductSite.tsx",
];

function loadExportComponents(): Record<string, string> {
  const dir = path.join(process.cwd(), "components", "product");
  const out: Record<string, string> = {};

  for (const file of PRODUCT_COMPONENT_FILES) {
    let content = fs.readFileSync(path.join(dir, file), "utf-8");

    content = content.replace(/@\/lib\/product-themes/g, "@/lib/product-themes");

    if (file === "ProductSite.tsx") {
      content = `import { siteConfig } from "@/lib/site-config";
import { ProductHome } from "./ProductHome";
import { ProductSiteShell } from "./ProductSiteShell";

export function ProductSite() {
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <ProductHome />
    </ProductSiteShell>
  );
}
`;
    }

    if (file === "ProductDetailsPage.tsx") {
      content = content.replace(
        /return "\/placeholder-product\.svg";/,
        'return "/product.jpg";',
      );
    }

    if (file === "ProductHero.tsx") {
      content = content.replace(
        /return "\/placeholder-product\.svg";/,
        'return "/product.jpg";',
      );
    }

    out[`components/${file}`] = content;
  }

  out["lib/product-paths.ts"] = fs.readFileSync(
    path.join(process.cwd(), "lib", "product-paths.ts"),
    "utf-8",
  );
  out["lib/product-legal.ts"] = fs.readFileSync(
    path.join(process.cwd(), "lib", "product-legal.ts"),
    "utf-8",
  );

  const themesPath = path.join(process.cwd(), "lib", "product-themes.ts");
  out["lib/product-themes.ts"] = fs.readFileSync(themesPath, "utf-8");

  const fontsPath = path.join(process.cwd(), "lib", "product-fonts.ts");
  out["lib/product-fonts.ts"] = fs.readFileSync(fontsPath, "utf-8");

  const layoutsPath = path.join(process.cwd(), "lib", "product-layouts.ts");
  out["lib/product-layouts.ts"] = fs.readFileSync(layoutsPath, "utf-8");

  const appearancePath = path.join(process.cwd(), "lib", "site-appearance.ts");
  out["lib/site-appearance.ts"] = fs.readFileSync(appearancePath, "utf-8");

  const backendDir = path.join(process.cwd(), "lib", "product-backend");
  for (const file of fs.readdirSync(backendDir)) {
    if (file.endsWith(".ts")) {
      out[`lib/product-backend/${file}`] = fs.readFileSync(
        path.join(backendDir, file),
        "utf-8",
      );
    }
  }

  out["lib/product-api-client.ts"] = fs.readFileSync(
    path.join(process.cwd(), "lib", "product-api-client.ts"),
    "utf-8",
  );

  const themeCssPath = path.join(process.cwd(), "components", "product", "product-theme.css");
  out["components/product-theme.css"] = fs.readFileSync(themeCssPath, "utf-8");

  const placeholderPath = path.join(process.cwd(), "public", "placeholder-product.svg");
  if (fs.existsSync(placeholderPath)) {
    out["public/placeholder-product.svg"] = fs.readFileSync(placeholderPath, "utf-8");
  }

  return out;
}

function loadStandaloneApiRoutes(): Record<string, string> {
  const sid = "STANDALONE_SITE_ID";
  const standalone = "true";

  const route = (
    file: string,
    method: string,
    handler: string,
    bodyParse = true,
  ) => {
    const parse = bodyParse
      ? "  const body = await req.json();\n"
      : "";
    return `import { NextResponse } from "next/server";
import { ${handler}, ${sid} } from "@/lib/product-backend/handlers";
import { jsonError } from "@/lib/product-backend/http";

export async function ${method}(${bodyParse ? "req: Request" : "_req: Request"}) {
${parse}  const result = await ${handler}(${sid}${bodyParse ? ", body" : ""}, ${standalone});
  if ("error" in result && result.ok === false) return jsonError(result.error);
  return NextResponse.json(result);
}
`;
  };

  return {
    "app/api/auth/session/route.ts": route(
      "session",
      "GET",
      "handleAuthSession",
      false,
    ),
    "app/api/auth/register/route.ts": route(
      "register",
      "POST",
      "handleAuthRegister",
    ),
    "app/api/auth/login/route.ts": route("login", "POST", "handleAuthLogin"),
    "app/api/auth/logout/route.ts": route(
      "logout",
      "POST",
      "handleAuthLogout",
      false,
    ),
    "app/api/cart/route.ts": `import { NextResponse } from "next/server";
import {
  handleAddCart,
  handleGetCart,
  handleRemoveCart,
  handleUpdateCart,
  STANDALONE_SITE_ID,
} from "@/lib/product-backend/handlers";
import { jsonError } from "@/lib/product-backend/http";

const standalone = true;

export async function GET() {
  return NextResponse.json(await handleGetCart(STANDALONE_SITE_ID, standalone));
}

export async function POST(req: Request) {
  const body = await req.json();
  const result = await handleAddCart(STANDALONE_SITE_ID, body, standalone);
  if (!result.ok) return jsonError(result.error);
  return NextResponse.json(result);
}

export async function PATCH(req: Request) {
  const body = await req.json();
  const result = await handleUpdateCart(STANDALONE_SITE_ID, body, standalone);
  if (!result.ok) return jsonError(result.error);
  return NextResponse.json(result);
}

export async function DELETE(req: Request) {
  const productId = new URL(req.url).searchParams.get("productId");
  if (!productId) return jsonError("productId is required.");
  return NextResponse.json(
    await handleRemoveCart(STANDALONE_SITE_ID, productId, standalone),
  );
}
`,
    "app/api/orders/route.ts": route("orders", "POST", "handleCheckout"),
    "app/api/orders/track/route.ts": route(
      "track",
      "POST",
      "handleTrackOrder",
    ),
    "app/api/orders/[orderId]/route.ts": `import { NextResponse } from "next/server";
import { handleGetOrder, STANDALONE_SITE_ID } from "@/lib/product-backend/handlers";
import { jsonError } from "@/lib/product-backend/http";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ orderId: string }> },
) {
  const { orderId } = await params;
  const email = new URL(req.url).searchParams.get("email") ?? "";
  if (!email) return jsonError("Email is required.", 400);
  const result = await handleGetOrder(STANDALONE_SITE_ID, orderId, email, true);
  if (!result.ok) return jsonError(result.error, 404);
  return NextResponse.json(result);
}
`,
    "app/api/contact/route.ts": route("contact", "POST", "handleContact"),
    "app/api/newsletter/route.ts": route(
      "newsletter",
      "POST",
      "handleNewsletter",
    ),
    "app/api/admin/dashboard/route.ts": `import { NextResponse } from "next/server";
import {
  handleAdminDashboard,
  handleAdminLogin,
  handleAdminLogout,
  STANDALONE_SITE_ID,
} from "@/lib/product-backend/handlers";
import { jsonError } from "@/lib/product-backend/http";

const standalone = true;

export async function GET() {
  const result = await handleAdminDashboard(STANDALONE_SITE_ID, standalone);
  if (!result.ok) return jsonError(result.error, 401);
  return NextResponse.json(result);
}

export async function POST(req: Request) {
  const body = await req.json();
  const result = await handleAdminLogin(STANDALONE_SITE_ID, body, standalone);
  if (!result.ok) return jsonError(result.error, 401);
  return NextResponse.json(result);
}

export async function DELETE() {
  await handleAdminLogout(STANDALONE_SITE_ID, standalone);
  return NextResponse.json({ ok: true });
}
`,
    "app/api/admin/orders/[orderId]/route.ts": `import { NextResponse } from "next/server";
import { handleAdminUpdateOrder, STANDALONE_SITE_ID } from "@/lib/product-backend/handlers";
import { jsonError } from "@/lib/product-backend/http";

export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ orderId: string }> },
) {
  const { orderId } = await params;
  const body = await req.json();
  const result = await handleAdminUpdateOrder(STANDALONE_SITE_ID, orderId, body, true);
  if (!result.ok) return jsonError(result.error, result.error.includes("auth") ? 401 : 404);
  return NextResponse.json(result);
}
`,
    ".env.example": `# Optional — set a strong secret in production
SESSION_SECRET=change-me-in-production
STORE_ADMIN_PASSWORD=store-admin
`,
  };
}

function loadStandalonePages(): Record<string, string> {
  return {
    "app/product/page.tsx": `import { ProductDetailsPage } from "@/components/ProductDetailsPage";
import { ProductSiteShell } from "@/components/ProductSiteShell";
import { siteConfig } from "@/lib/site-config";

export default function ProductPage() {
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <ProductDetailsPage />
    </ProductSiteShell>
  );
}
`,
    "app/orders/[orderId]/page.tsx": `import { OrderDetailsPage } from "@/components/OrderDetailsPage";
import { ProductSiteShell } from "@/components/ProductSiteShell";
import { siteConfig } from "@/lib/site-config";

export default async function OrderPage({
  params,
  searchParams,
}: {
  params: Promise<{ orderId: string }>;
  searchParams: Promise<{ email?: string }>;
}) {
  const { orderId } = await params;
  const { email } = await searchParams;
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <OrderDetailsPage orderId={orderId} email={email} />
    </ProductSiteShell>
  );
}
`,
    "app/privacy/page.tsx": `import { LegalPageView } from "@/components/LegalPageView";
import { ProductSiteShell } from "@/components/ProductSiteShell";
import { privacyPolicyBody } from "@/lib/product-legal";
import { siteConfig } from "@/lib/site-config";

export default function PrivacyPage() {
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <LegalPageView title="Privacy Policy" body={privacyPolicyBody(siteConfig)} />
    </ProductSiteShell>
  );
}
`,
    "app/terms/page.tsx": `import { LegalPageView } from "@/components/LegalPageView";
import { ProductSiteShell } from "@/components/ProductSiteShell";
import { termsOfServiceBody } from "@/lib/product-legal";
import { siteConfig } from "@/lib/site-config";

export default function TermsPage() {
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <LegalPageView title="Terms of Service" body={termsOfServiceBody(siteConfig)} />
    </ProductSiteShell>
  );
}
`,
    "app/dashboard/page.tsx": `import { PaymentDashboardPage } from "@/components/PaymentDashboardPage";
import { ProductSiteShell } from "@/components/ProductSiteShell";
import { siteConfig } from "@/lib/site-config";

export default function DashboardPage() {
  return (
    <ProductSiteShell config={siteConfig} apiBase="/api" basePath="">
      <PaymentDashboardPage />
    </ProductSiteShell>
  );
}
`,
  };
}

function buildLayoutTsx(config: ProductSiteConfig): string {
  return `import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: ${escapeJson(config.productName + " | " + config.brandName)},
  description: ${escapeJson(config.productDescription)},
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={\`\${geist.variable} antialiased\`}>
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
`;
}

export async function generateSiteZip(config: ProductSiteConfig): Promise<Buffer> {
  const zip = new JSZip();
  const rootName =
    config.brandName.toLowerCase().replace(/\s+/g, "-") + "-site";
  const root = zip.folder(rootName)!;

  root.file("package.json", buildPackageJson(config));
  root.file("README.md", buildReadme(config));
  root.file("lib/site-config.ts", buildSiteConfigFile(config));
  root.file("app/layout.tsx", buildLayoutTsx(config));

  for (const [path, content] of Object.entries(STATIC_FILES)) {
    root.file(path, content);
  }

  for (const [path, content] of Object.entries(loadExportComponents())) {
    root.file(path, content);
  }

  for (const [path, content] of Object.entries(loadStandaloneApiRoutes())) {
    root.file(path, content);
  }

  for (const [path, content] of Object.entries(loadStandalonePages())) {
    root.file(path, content);
  }

  if (config.imageBase64) {
    const ext = config.imageMimeType.includes("png") ? "png" : "jpg";
    const imageBuffer = Buffer.from(config.imageBase64, "base64");
    root.file(`public/product.${ext}`, imageBuffer);
  } else {
    const placeholderSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800">
  <rect fill="#f0ebe3" width="800" height="800"/>
  <text x="400" y="400" text-anchor="middle" dominant-baseline="middle" fill="#8b6914" font-family="serif" font-size="32">${config.productName}</text>
</svg>`;
    root.file("public/product.jpg", placeholderSvg);
  }

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
  return zipBuffer;
}
