import fs from "fs";
import path from "path";
import JSZip from "jszip";
import type { ProductSiteConfig } from "./types";

function escapeJson(str: string): string {
  return JSON.stringify(str);
}

export function buildSiteConfigFile(config: ProductSiteConfig): string {
  const siteConfig = {
    brandName: config.brandName,
    productName: config.productName,
    tagline: config.tagline,
    heroHeadline: config.heroHeadline,
    heroSubtext: config.heroSubtext,
    ctaText: config.ctaText,
    price: config.price,
    shippingMessage: config.shippingMessage,
    rating: config.rating,
    reviewCount: config.reviewCount,
    productDescription: config.productDescription,
    statsTitle: config.statsTitle,
    statsSubtitle: config.statsSubtitle,
    stats: config.stats,
    contactEmail: config.contactEmail,
    footerCopyright: config.footerCopyright,
    themeId: config.themeId || "classic",
    fontPairId: config.fontPairId || "inter",
    customAccentColor: config.customAccentColor || "",
    customButtonColor: config.customButtonColor || "",
    customBackgroundColor: config.customBackgroundColor || "",
    customTextColor: config.customTextColor || "",
  };

  return `export const siteConfig = ${JSON.stringify(siteConfig, null, 2)} as const;

export type SiteConfig = typeof siteConfig;
`;
}

export function buildReadme(config: ProductSiteConfig): string {
  const slug = config.brandName.toLowerCase().replace(/\s+/g, "-");
  return `# ${config.brandName} — Product Website

A Next.js product landing page generated by **Website Maker**.

## Prerequisites

- [Node.js](https://nodejs.org/) 18.17 or later
- npm (included with Node.js)

## Quick Start

1. **Extract** this folder if you downloaded it as a ZIP.

2. **Open a terminal** in this project folder (\`${slug}-site\`).

3. **Install dependencies:**

   \`\`\`bash
   npm install
   \`\`\`

4. **Start the development server:**

   \`\`\`bash
   npm run dev
   \`\`\`

5. **Open your browser** and visit [http://localhost:3000](http://localhost:3000).

## Production Build

To create an optimized production build:

\`\`\`bash
npm run build
npm start
\`\`\`

The site will be available at [http://localhost:3000](http://localhost:3000).

## Customize Content

Edit \`lib/site-config.ts\` to update product copy, stats, pricing, and contact details without touching component code.

Replace \`public/product.jpg\` with your own product image (recommended: square, at least 800×800px).

## Project Structure

\`\`\`
├── app/
│   ├── layout.tsx      # Root layout & metadata
│   ├── page.tsx        # Main landing page
│   └── globals.css     # Global styles
├── components/         # UI sections (hero, stats, contact, footer)
├── lib/
│   └── site-config.ts  # All product content — edit this file
└── public/
    └── product.jpg     # Product image
\`\`\`

## Deploy

This is a standard Next.js app. Deploy to [Vercel](https://vercel.com), Netlify, or any Node.js host:

\`\`\`bash
npm run build
\`\`\`

---

Generated for **${config.productName}** · ${config.brandName}
`;
}

function buildPackageJson(config: ProductSiteConfig): string {
  const name = config.brandName.toLowerCase().replace(/\s+/g, "-") + "-site";
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "eslint",
      },
      dependencies: {
        next: "16.2.9",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        eslint: "^9",
        "eslint-config-next": "16.2.9",
        tailwindcss: "^4",
        typescript: "^5",
      },
    },
    null,
    2,
  );
}

const STATIC_FILES: Record<string, string> = {
  "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,
  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ),
  "postcss.config.mjs": `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`,
  "eslint.config.mjs": `import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([".next/**", "out/**", "build/**", "next-env.d.ts"]),
]);

export default eslintConfig;
`,
  "next-env.d.ts": `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
  ".gitignore": `# dependencies
/node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files
.env*

# typescript
*.tsbuildinfo
next-env.d.ts
`,
  "app/globals.css": `@import "tailwindcss";

:root {
  --background: #faf8f5;
  --foreground: #1a1a1a;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}

body {
  background: var(--background);
  color: var(--foreground);
}
`,
  "app/page.tsx": `import { ProductSite } from "@/components/ProductSite";

export default function Home() {
  return <ProductSite />;
}
`,
};

const PRODUCT_COMPONENT_FILES = [
  "ProductSiteContext.tsx",
  "ProductFontLoader.tsx",
  "Modal.tsx",
  "SiteModals.tsx",
  "ProductHeader.tsx",
  "ProductHero.tsx",
  "StatsSection.tsx",
  "ContactForm.tsx",
  "ProductFooter.tsx",
  "ProductSite.tsx",
];

function loadExportComponents(): Record<string, string> {
  const dir = path.join(process.cwd(), "components", "product");
  const out: Record<string, string> = {};

  for (const file of PRODUCT_COMPONENT_FILES) {
    let content = fs.readFileSync(path.join(dir, file), "utf-8");

    content = content.replace(/@\/lib\/product-themes/g, "@/lib/product-themes");

    if (file === "ProductSite.tsx") {
      content = content
        .replace(
          /import type \{ ProductSiteConfig \} from "@\/lib\/types";\n/,
          'import { siteConfig } from "@/lib/site-config";\n',
        )
        .replace(
          /export function ProductSite\(\{ config \}: \{ config: ProductSiteConfig \}\)/,
          "export function ProductSite()",
        )
        .replace(/config\.fontPairId/g, "siteConfig.fontPairId")
        .replace(/resolveSiteStyle\(config\)/g, "resolveSiteStyle(siteConfig)")
        .replace(
          /<ProductSiteProvider config=\{config\}>/,
          "<ProductSiteProvider config={siteConfig}>",
        );
    }

    if (file === "ProductHero.tsx") {
      content = content
        .replace(
          /function getImageSrc[\s\S]*?\n\}\n\n/,
          'import Image from "next/image";\n\n',
        )
        .replace(
          /const imageSrc = getImageSrc[\s\S]*?;\n\n/,
          "",
        )
        .replace(
          /<button[\s\S]*?<img[\s\S]*?\/>\n          <\/button>/,
          `<button
            type="button"
            onClick={addToCart}
            className="relative aspect-square w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-xl transition hover:shadow-2xl active:scale-[0.99]"
          >
            <Image
              src="/product.jpg"
              alt={config.productName}
              fill
              className="object-cover"
              priority
            />
          </button>`,
        );
    }

    out[`components/${file}`] = content;
  }

  const themesPath = path.join(process.cwd(), "lib", "product-themes.ts");
  out["lib/product-themes.ts"] = fs.readFileSync(themesPath, "utf-8");

  const fontsPath = path.join(process.cwd(), "lib", "product-fonts.ts");
  out["lib/product-fonts.ts"] = fs.readFileSync(fontsPath, "utf-8");

  const appearancePath = path.join(process.cwd(), "lib", "site-appearance.ts");
  out["lib/site-appearance.ts"] = fs.readFileSync(appearancePath, "utf-8");

  const themeCssPath = path.join(process.cwd(), "components", "product", "product-theme.css");
  out["components/product-theme.css"] = fs.readFileSync(themeCssPath, "utf-8");

  const placeholderPath = path.join(process.cwd(), "public", "placeholder-product.svg");
  if (fs.existsSync(placeholderPath)) {
    out["public/placeholder-product.svg"] = fs.readFileSync(placeholderPath, "utf-8");
  }

  return out;
}

function buildLayoutTsx(config: ProductSiteConfig): string {
  return `import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: ${escapeJson(config.productName + " | " + config.brandName)},
  description: ${escapeJson(config.productDescription)},
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={\`\${geist.variable} antialiased\`}>
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
`;
}

export async function generateSiteZip(config: ProductSiteConfig): Promise<Buffer> {
  const zip = new JSZip();
  const rootName =
    config.brandName.toLowerCase().replace(/\s+/g, "-") + "-site";
  const root = zip.folder(rootName)!;

  root.file("package.json", buildPackageJson(config));
  root.file("README.md", buildReadme(config));
  root.file("lib/site-config.ts", buildSiteConfigFile(config));
  root.file("app/layout.tsx", buildLayoutTsx(config));

  for (const [path, content] of Object.entries(STATIC_FILES)) {
    root.file(path, content);
  }

  for (const [path, content] of Object.entries(loadExportComponents())) {
    root.file(path, content);
  }

  if (config.imageBase64) {
    const ext = config.imageMimeType.includes("png") ? "png" : "jpg";
    const imageBuffer = Buffer.from(config.imageBase64, "base64");
    root.file(`public/product.${ext}`, imageBuffer);
  } else {
    const placeholderSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800">
  <rect fill="#f0ebe3" width="800" height="800"/>
  <text x="400" y="400" text-anchor="middle" dominant-baseline="middle" fill="#8b6914" font-family="serif" font-size="32">${config.productName}</text>
</svg>`;
    root.file("public/product.jpg", placeholderSvg);
  }

  const zipBuffer = await zip.generateAsync({ type: "nodebuffer" });
  return zipBuffer;
}
