export interface ProductTheme {
  id: string;
  name: string;
  description: string;
  preview: [string, string, string];
  vars: Record<string, string>;
}

export const PRODUCT_THEMES: ProductTheme[] = [
  {
    id: "classic",
    name: "Classic Gold",
    description: "Warm cream & gold — Corevita-style wellness",
    preview: ["#faf8f5", "#8b6914", "#1a1a1a"],
    vars: {
      "--ps-banner-bg": "#1a1a1a",
      "--ps-banner-text": "#ffffff",
      "--ps-header-bg": "rgba(250, 248, 245, 0.95)",
      "--ps-header-border": "#e8e4dc",
      "--ps-page-bg": "#ffffff",
      "--ps-section-bg": "#faf8f5",
      "--ps-section-alt": "#ffffff",
      "--ps-text": "#1a1a1a",
      "--ps-text-muted": "#555555",
      "--ps-text-subtle": "#888888",
      "--ps-accent": "#8b6914",
      "--ps-accent-hover": "#6d5210",
      "--ps-star": "#d4a017",
      "--ps-btn-bg": "#1a1a1a",
      "--ps-btn-hover": "#333333",
      "--ps-btn-text": "#ffffff",
      "--ps-border": "#e8e4dc",
      "--ps-input-border": "#d4cfc5",
      "--ps-card-bg": "#faf8f5",
      "--ps-stat-accent": "#8b6914",
      "--ps-badge-bg": "#8b6914",
      "--ps-highlight-bg": "#f0ebe3",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark mode with electric blue accents",
    preview: ["#0f172a", "#38bdf8", "#1e293b"],
    vars: {
      "--ps-banner-bg": "#020617",
      "--ps-banner-text": "#e2e8f0",
      "--ps-header-bg": "rgba(15, 23, 42, 0.95)",
      "--ps-header-border": "#1e293b",
      "--ps-page-bg": "#0f172a",
      "--ps-section-bg": "#1e293b",
      "--ps-section-alt": "#0f172a",
      "--ps-text": "#f1f5f9",
      "--ps-text-muted": "#94a3b8",
      "--ps-text-subtle": "#64748b",
      "--ps-accent": "#38bdf8",
      "--ps-accent-hover": "#0ea5e9",
      "--ps-star": "#fbbf24",
      "--ps-btn-bg": "#38bdf8",
      "--ps-btn-hover": "#0ea5e9",
      "--ps-btn-text": "#0f172a",
      "--ps-border": "#334155",
      "--ps-input-border": "#475569",
      "--ps-card-bg": "#1e293b",
      "--ps-stat-accent": "#38bdf8",
      "--ps-badge-bg": "#0ea5e9",
      "--ps-highlight-bg": "#334155",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Fresh blues and seafoam greens",
    preview: ["#f0f9ff", "#0284c7", "#0d9488"],
    vars: {
      "--ps-banner-bg": "#0c4a6e",
      "--ps-banner-text": "#e0f2fe",
      "--ps-header-bg": "rgba(240, 249, 255, 0.95)",
      "--ps-header-border": "#bae6fd",
      "--ps-page-bg": "#ffffff",
      "--ps-section-bg": "#f0f9ff",
      "--ps-section-alt": "#ffffff",
      "--ps-text": "#0c4a6e",
      "--ps-text-muted": "#475569",
      "--ps-text-subtle": "#64748b",
      "--ps-accent": "#0284c7",
      "--ps-accent-hover": "#0369a1",
      "--ps-star": "#0d9488",
      "--ps-btn-bg": "#0284c7",
      "--ps-btn-hover": "#0369a1",
      "--ps-btn-text": "#ffffff",
      "--ps-border": "#bae6fd",
      "--ps-input-border": "#7dd3fc",
      "--ps-card-bg": "#e0f2fe",
      "--ps-stat-accent": "#0d9488",
      "--ps-badge-bg": "#0d9488",
      "--ps-highlight-bg": "#e0f2fe",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Natural greens and earthy tones",
    preview: ["#f0fdf4", "#166534", "#14532d"],
    vars: {
      "--ps-banner-bg": "#14532d",
      "--ps-banner-text": "#dcfce7",
      "--ps-header-bg": "rgba(240, 253, 244, 0.95)",
      "--ps-header-border": "#bbf7d0",
      "--ps-page-bg": "#ffffff",
      "--ps-section-bg": "#f0fdf4",
      "--ps-section-alt": "#ffffff",
      "--ps-text": "#14532d",
      "--ps-text-muted": "#4b5563",
      "--ps-text-subtle": "#6b7280",
      "--ps-accent": "#166534",
      "--ps-accent-hover": "#14532d",
      "--ps-star": "#ca8a04",
      "--ps-btn-bg": "#166534",
      "--ps-btn-hover": "#14532d",
      "--ps-btn-text": "#ffffff",
      "--ps-border": "#bbf7d0",
      "--ps-input-border": "#86efac",
      "--ps-card-bg": "#dcfce7",
      "--ps-stat-accent": "#166534",
      "--ps-badge-bg": "#16a34a",
      "--ps-highlight-bg": "#dcfce7",
    },
  },
  {
    id: "rose",
    name: "Rose",
    description: "Soft blush pink and warm neutrals",
    preview: ["#fff1f2", "#be123c", "#881337"],
    vars: {
      "--ps-banner-bg": "#881337",
      "--ps-banner-text": "#ffe4e6",
      "--ps-header-bg": "rgba(255, 241, 242, 0.95)",
      "--ps-header-border": "#fecdd3",
      "--ps-page-bg": "#ffffff",
      "--ps-section-bg": "#fff1f2",
      "--ps-section-alt": "#ffffff",
      "--ps-text": "#881337",
      "--ps-text-muted": "#6b7280",
      "--ps-text-subtle": "#9ca3af",
      "--ps-accent": "#be123c",
      "--ps-accent-hover": "#9f1239",
      "--ps-star": "#f59e0b",
      "--ps-btn-bg": "#be123c",
      "--ps-btn-hover": "#9f1239",
      "--ps-btn-text": "#ffffff",
      "--ps-border": "#fecdd3",
      "--ps-input-border": "#fda4af",
      "--ps-card-bg": "#ffe4e6",
      "--ps-stat-accent": "#be123c",
      "--ps-badge-bg": "#e11d48",
      "--ps-highlight-bg": "#ffe4e6",
    },
  },
  {
    id: "violet",
    name: "Violet Mint",
    description: "Purple & green — matches Website Maker",
    preview: ["#f5f3ff", "#7c3aed", "#059669"],
    vars: {
      "--ps-banner-bg": "#4c1d95",
      "--ps-banner-text": "#ede9fe",
      "--ps-header-bg": "rgba(245, 243, 255, 0.95)",
      "--ps-header-border": "#ddd6fe",
      "--ps-page-bg": "#ffffff",
      "--ps-section-bg": "#f5f3ff",
      "--ps-section-alt": "#ecfdf5",
      "--ps-text": "#1e1b2e",
      "--ps-text-muted": "#52525b",
      "--ps-text-subtle": "#71717a",
      "--ps-accent": "#7c3aed",
      "--ps-accent-hover": "#6d28d9",
      "--ps-star": "#059669",
      "--ps-btn-bg": "#7c3aed",
      "--ps-btn-hover": "#6d28d9",
      "--ps-btn-text": "#ffffff",
      "--ps-border": "#ddd6fe",
      "--ps-input-border": "#c4b5fd",
      "--ps-card-bg": "#ede9fe",
      "--ps-stat-accent": "#059669",
      "--ps-badge-bg": "#059669",
      "--ps-highlight-bg": "#ede9fe",
    },
  },
];

export const DEFAULT_THEME_ID = "classic";

export function getProductTheme(themeId?: string): ProductTheme {
  return (
    PRODUCT_THEMES.find((t) => t.id === themeId) ??
    PRODUCT_THEMES.find((t) => t.id === DEFAULT_THEME_ID)!
  );
}

export function themeStyle(themeId?: string): Record<string, string> {
  return getProductTheme(themeId).vars;
}
